### ISSUE TITLE
Dawn: "requiredFeaturesCount" vs "requiredFeatureCount"? 

### ISSUE THREAD

**Issue by eliasdaler** [eliemichel/LearnWebGPU#51]
It seems like Google Dawn uses `requiredFeatureCount` and not `requiredFeaturesCount` as specified in tutorial for `WGPUDeviceDescriptor`. Is it something that has changed recently?

**Comment by eliasdaler** [comment]
Also this doesn't work:

`renderPassDesc.timestampWriteCount = 0;` - `timestampWriteCount` doesn't exist in Dawn.

(It seems like Dawn/webgpu is moving fast, so I think there will be many more inconsistencies that I'll post here as I go through the tutorial)

**Comment by eliemichel** [comment]
These are recent changes. I am not updating the guide as long as Dawn does not really switch to the new standard API, where there is no longer the SwapChain, because I know it will happen and don't want to duplicate the effort (each update takes time because I have to process all chapters).

Moreover, if I update for Dawn, I also want to update for wgpu-native, but currently the two implementations are less in sync that they used to be (again, because Dawn lags behind on the SwapChain part) so it'd be a mess to have suddenly a lot of `#if`, that I would have to revert back soon again.

**Comment by eliemichel** [comment]
(It's been upgraded)
